TOKEN: 
 - ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ
 - ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ
CHANNEL: 
 - 1234567890123456789
 - 1234567890123456789
MODE: quote
LANG: en
REPLY: true
DELETE: true
DELAY: 60
REPOST: 100
